version: '3.8'

services:
  google-scholar-mcp:
    build: .
    container_name: google-scholar-mcp-server
    environment:
      - SCRAPINGDOG_API_KEY=${SCRAPINGDOG_API_KEY:-}
    # 可选：如果需要通过 socket 或端口暴露
    # ports:
    #   - "8000:8000"
    restart: unless-stopped
    # 对于 MCP 可能需要 stdin_open 和 tty
    stdin_open: true
    tty: true
    # 默认服务：无 profile 标签，docker-compose up 直接启动

  google-scholar-mcp-ephemeral:
    build: .
    environment:
      - SCRAPINGDOG_API_KEY=${SCRAPINGDOG_API_KEY:-}
    stdin_open: true
    tty: true
    restart: no  # 不自动重启
    profiles: ["ephemeral"]  # 临时模式：需要 docker-compose --profile ephemeral up 启动
